spring.application.name=banking-app
spring.profiles.active=prod


spring.datasource.url=jdbc:h2:mem:authdb
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

spring.h2.console.path=/h2-console
# ============ GOOGLE OAUTH BLOCK START ============
# Delete/comment this whole block if the OAUTH block in SecurityConfig is also disabled
spring.security.oauth2.client.registration.google.client-id={$GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret={GOOGLE_SECRET_KEY}
spring.security.oauth2.client.registration.google.scope=email,profile
# ============ GOOGLE OAUTH BLOCK END ============

# Toggle JWT security on/off without touching code
app.security.jwt.enabled=true


# Customize the Swagger UI path (default is /swagger-ui.html, this is just if you want something else)
springdoc.swagger-ui.path=/swagger-ui.html

# Sort endpoints alphabetically within each tag, easier to scan for students
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha